name: Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  NAME: "tau-release"
  VERSION: "1.1"
  ARCH: "noarch"
  TAUOS_VERSION: "1.1"

jobs:
  build:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: ${{ env.NAME }}
      version: ${{ env.VERSION }}
      arch: ${{ env.ARCH }}
      tauOSVersion: ${{ env.TAUOS_VERSION }}
      extraBuildPackages: systemd-rpm-macros
  sign:
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    with:
      name: ${{ env.NAME }}
      version: ${{ env.VERSION }}
      arch: ${{ env.ARCH }}
      tauOSVersion: ${{ env.TAUOS_VERSION }}
