name: Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "tau-release.spec"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: RPMs
        path: ${{ steps.rpm.outputs.rpm_dir_path }}
