name: Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: "tau-release"
  PACKAGE_VERSION: "1.1"
  PACKAGE_ARCH: "noarch"
  TAUOS_VERSION: "1.1"
  
jobs:
  build:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      extraBuildPackages: systemd-rpm-macros
  sign:
    needs:
      - build
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
