name: Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: tau-OS/github-actions/.github/workflows/build-rpm.yml@main
    with:
      name: "tau-release"
      version: "1.1"
      arch: "noarch"
      tauOSVersion: "1.1"
      extraBuildPackages: systemd-rpm-macros
  sign:
    uses: tau-OS/github-actions/.github/workflows/sign-rpm.yml@main
    with:
      name: "tau-release"
      version: "1.1"
      arch: "noarch"
      tauOSVersion: "1.1"
